MPPI:
  ros__parameters:
    visualize: False
    waypoint_path: "waypoints.csv"

    # Publisher Parameters
    drive_topic: "/drive"
    occupancy_topic: "/occupancy"
    cost_map_topic: "/cost_map"
    marker_topic: "/trajectory"

    # Subscriber Parameters
    pose_topic: "ego_racecar/odom"
    scan_topic: "/scan"

    # Model Parameters
    wheelbase: 0.33 # Wheelbase (m)
    min_throttle: 1.3 # Minimum throttle (m/s)
    max_throttle: 1.3 # Maximum throttle (m/s)
    max_steer: 0.4189 # Maximum steer (rad)
    dt: 0.05 # Timestep (s)

    # MPPI Parameters
    num_trajectories: 50
    steps_trajectories: 30
    v_sigma: 2.0
    omega_sigma: 0.25

    # Cost Map Parameters
    dist_cost_mult: 17
    obstacle_weight: 0.5
    raceline_weight: 0.5
