MPPI:
  ros__parameters:
    visualize: False
    waypoint_path: "aims_lockers.csv"
    vehicle_frame: "ego_racecar/base_link"

    # Publisher Parameters
    drive_topic: "/drive"
    occupancy_topic: "/occupancy"
    cost_map_topic: "/cost_map"
    marker_topic: "/trajectory"

    # Subscriber Parameters
    pose_topic: "ego_racecar/odom"
    scan_topic: "/scan"

    # Model Parameters
    wheelbase: 0.33 # Wheelbase (m)
    min_throttle: 0.5 # Minimum throttle (m/s)
    max_throttle: 0.5 # Maximum throttle (m/s)
    max_steer: 0.4189 # Maximum steer (rad)
    dt: 0.1 # Timestep (s)

    # MPPI Parameters
    num_trajectories: 25
    steps_trajectories: 5
    v_sigma: 0.05
    omega_sigma: 0.25

    # Cost Map Parameters
    cost_map_width: 100
    cost_map_res: 0.03
    dist_cost_mult: 13
    obstacle_weight: 10.0
    raceline_weight: 0.2
    obstacle_dilation: 15
    raceline_dilation: 3

    # Trajectory Evaluation Parameters
    position_weight: 1.0
    heading_weight: 1.0
