MPPI:
  ros__parameters:
    visualize: False
    waypoint_path: "waypoints.csv"
    vehicle_frame: "ego_racecar/base_link"

    # Publisher Parameters
    drive_topic: "/drive"
    occupancy_topic: "/occupancy"
    cost_map_topic: "/cost_map"
    marker_topic: "/trajectory"

    # Subscriber Parameters
    pose_topic: "ego_racecar/odom"
    scan_topic: "/scan"

    # Model Parameters
    wheelbase: 0.33 # Wheelbase (m)
    min_throttle: 1.3 # Minimum throttle (m/s)
    max_throttle: 3 # Maximum throttle (m/s)
    max_steer: 0.4189 # Maximum steer (rad)
    dt: 0.05 # Timestep (s)

    # MPPI Parameters
    num_trajectories: 50
    steps_trajectories: 30
    v_sigma: 0.05
    omega_sigma: 0.1

    # Cost Map Parameters
    cost_map_width: 100
    cost_map_res: 0.03
    dist_cost_mult: 17
    obstacle_weight: 1.0
    raceline_weight: 0.23
    obstacle_dilation: 15
    raceline_dilation: 3
