MPPI:
  ros__parameters:
    # Publisher Parameters
    drive_topic: "/drive"
    occupancy_topic: "/occupancy"
    marker_topic: "/trajectory"

    # Subscriber Parameters
    pose_topic: "ego_racecar/odom"
    scan_topic: "/scan"

    waypoint_path: "waypoints.csv"

    # Model Parameters
    wheelbase: 0.33 # Wheelbase (m)
    min_throttle: 1.0 # Minimum throttle (m/s)
    max_throttle: 5.0 # Maximum throttle (m/s)
    max_steer: 0.4189 # Maximum steer (rad)
    dt: 0.1 # Timestep (s)