MPPI:
  ros__parameters:
    visualize: True
    waypoint_path: "waypoints.csv"

    # Publisher Parameters
    drive_topic: "/drive"
    occupancy_topic: "/occupancy"
    cost_map_topic: "/cost_map"
    marker_topic: "/trajectory"

    # Subscriber Parameters
    pose_topic: "ego_racecar/odom"
    scan_topic: "/scan"

    # Model Parameters
    wheelbase: 0.33 # Wheelbase (m)
    min_throttle: 1.0 # Minimum throttle (m/s)
    max_throttle: 5.0 # Maximum throttle (m/s)
    max_steer: 0.4189 # Maximum steer (rad)
    dt: 0.1 # Timestep (s)

    # MPPI Parameters
    num_trajectories: 10
    steps_trajectories: 10

    # Cost Map Parameters
    dist_cost_mult: 10
    obstacle_weight: 0.5
    raceline_weight: 0.5